(()=> {
  const API='https://avvgbxvfrjrmbuvrymnh.supabase.co/functions/v1/switch-to-switch';
  const KEY='s2s_support_chat_v1';
  const style=document.createElement('style');
  style.textContent='#s2s-support-root{position:fixed;z-index:99999;left:18px;top:18px;direction:rtl;font-family:Tahoma,Arial,sans-serif;color:#eef5ff}#s2s-support-toggle{border:1px solid #7db4ff;background:linear-gradient(135deg,#2563eb,#4338ca);color:#fff;border-radius:16px;padding:14px 18px;font:800 14px Tahoma;box-shadow:0 12px 32px #02081766;cursor:pointer;display:flex;gap:9px;align-items:center}#s2s-support-panel{display:none;position:absolute;top:64px;left:0;width:min(350px,calc(100vw - 28px));max-height:min(560px,calc(100dvh - 110px));overflow:hidden;background:#0b1729;border:1px solid #29415f;border-radius:20px;box-shadow:0 24px 70px #0009}#s2s-support-panel.open{display:flex;flex-direction:column}#s2s-support-root.open #s2s-support-toggle{display:none}#s2s-support-root.open #s2s-support-panel{top:0}.s2sh{padding:16px;background:linear-gradient(135deg,#123765,#1d4ed8);display:flex;justify-content:space-between;align-items:center}.s2sh strong{font-size:15px}.s2sh small{display:block;color:#dbeafe;font-size:10px;margin-top:5px}.s2sclose{background:#ffffff20;color:#fff;border:0;border-radius:9px;padding:7px 10px;cursor:pointer;font-size:17px}.s2sbody{padding:15px;overflow:auto;min-height:120px}.s2schoice{display:block;width:100%;text-align:right;padding:14px;margin:0 0 10px;border-radius:13px;border:1px solid #29415f;background:#10233b;color:#fff;font:700 13px Tahoma;cursor:pointer}.s2schoice:hover{border-color:#60a5fa;background:#142d4b}.s2schoice span{display:block;font-size:11px;font-weight:400;color:#9fb5ce;margin-top:5px}.s2slabel{display:block;font-size:12px;font-weight:700;margin:8px 0}.s2sinput,.s2stext{width:100%;box-sizing:border-box;padding:12px;border-radius:11px;border:1px solid #29415f;background:#071321;color:#fff;font:13px Tahoma;outline:none}.s2sbutton{border:0;border-radius:11px;padding:12px 14px;background:#2563eb;color:#fff;font:800 12px Tahoma;cursor:pointer}.s2sbutton:disabled{opacity:.5;cursor:wait}.s2snote{color:#91a6bf;font-size:10px;line-height:1.9;margin:10px 0}.s2serr{color:#fca5a5;font-size:11px;line-height:1.8;margin:8px 0}.s2schat{display:flex;flex-direction:column;gap:8px;min-height:160px;max-height:260px;overflow:auto;padding:4px 0 12px}.s2smsg{max-width:88%;padding:10px 11px;border-radius:12px;font-size:12px;line-height:1.9;white-space:pre-wrap;overflow-wrap:anywhere}.s2smsg.customer{align-self:flex-start;background:#18365a;color:#eff6ff;border-bottom-right-radius:3px}.s2smsg.admin{align-self:flex-end;background:#0e574b;color:#d1fae5;border-bottom-left-radius:3px}.s2stime{display:block;font-size:9px;opacity:.65;margin-top:3px}.s2sform{display:flex;gap:7px;align-items:flex-end}.s2sform textarea{resize:vertical;min-height:42px;max-height:100px;flex:1}@media(max-width:480px){#s2s-support-root{left:12px;top:12px}#s2s-support-toggle{padding:12px 15px}}';
  document.head.appendChild(style);
  const root=document.createElement('div');root.id='s2s-support-root';
  root.innerHTML='<button id="s2s-support-toggle" type="button">🎧 پشتیبانی</button><section id="s2s-support-panel" aria-label="پشتیبانی"><header class="s2sh"><div><strong>پشتیبانی سوییچ به سوییچ</strong><small>برای راهنمایی در کنار شما هستیم</small></div><button class="s2sclose" id="s2s-support-close" type="button" aria-label="بستن">×</button></header><div class="s2sbody" id="s2s-support-body"></div></section>';
  document.body.appendChild(root);
  const panel=root.querySelector('#s2s-support-panel'),body=root.querySelector('#s2s-support-body');
  let poller=null,session=null,messagesSignature='';
  try{session=JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalize=s=>String(s).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[\s()-]/g,'');
  async function api(name,opts={}){const r=await fetch(API+'?api='+name+(opts.query||''),{method:opts.method||'GET',headers:{'content-type':'application/json'},body:opts.body?JSON.stringify(opts.body):undefined,cache:'no-store'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'ارتباط با سرور برقرار نشد');return j}
  function stopPolling(){if(poller){clearInterval(poller);poller=null}}
  function home(){stopPolling();body.innerHTML='<button class="s2schoice" id="s2s-call" type="button">📞 تماس با پشتیبانی<span>برای تماس مستقیم بزنید</span></button><button class="s2schoice" id="s2s-chat-start" type="button">💬 چت با پشتیبانی<span>پیام بفرستید و پاسخ را همین‌جا دریافت کنید</span></button><p class="s2snote">در چت، شماره موبایل شما برای شناسایی گفت‌وگو و پیگیری درخواست استفاده می‌شود.</p>';body.querySelector('#s2s-call').onclick=()=>{location.href='tel:09004258657'};body.querySelector('#s2s-chat-start').onclick=()=>{if(session?.id&&session?.token){chatView();refreshMessages();return}phoneForm()}}
  function phoneForm(){stopPolling();body.innerHTML='<form id="s2s-phone-form"><label class="s2slabel" for="s2s-phone">شماره موبایل شما</label><input class="s2sinput" id="s2s-phone" name="mobile" inputmode="tel" autocomplete="tel" maxlength="16" placeholder="مثلاً ۰۹۱۲۱۲۳۴۵۶۷" required><p class="s2snote">شماره شما نام گفت‌وگو خواهد بود تا پشتیبانی بتواند پیام‌هایتان را پیگیری کند.</p><div id="s2s-phone-error" class="s2serr"></div><button class="s2sbutton" type="submit">ورود به چت ←</button></form>';body.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button'),err=body.querySelector('#s2s-phone-error'),mobile=normalize(body.querySelector('#s2s-phone').value);if(!/^\+?[0-9]{10,15}$/.test(mobile)){err.textContent='لطفاً شماره موبایل معتبر وارد کن.';return}btn.disabled=true;err.textContent='در حال اتصال...';try{const j=await api('support-start',{method:'POST',body:{mobile}});session={id:j.conversation.id,token:j.token,mobile:j.conversation.customer_mobile};localStorage.setItem(KEY,JSON.stringify(session));chatView();await refreshMessages()}catch(x){err.textContent=x.message}finally{btn.disabled=false}}}
  function chatView(){stopPolling();messagesSignature='';body.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px"><b style="font-size:12px">گفت‌وگو با پشتیبانی</b><button class="s2sclose" id="s2s-new-chat" type="button" style="font-size:10px">گفت‌وگوی جدید</button></div><div class="s2schat" id="s2s-messages"><div class="s2snote">در حال دریافت پیام‌ها...</div></div><form class="s2sform" id="s2s-send-form"><textarea class="s2stext" id="s2s-message" maxlength="3000" placeholder="پیامت را بنویس..." required></textarea><button class="s2sbutton" type="submit">ارسال</button></form><div id="s2s-chat-error" class="s2serr"></div>';body.querySelector('#s2s-new-chat').onclick=()=>{if(confirm('یک گفت‌وگوی تازه بسازیم؟')){session=null;localStorage.removeItem(KEY);phoneForm()}};body.querySelector('#s2s-send-form').onsubmit=async e=>{e.preventDefault();const input=body.querySelector('#s2s-message'),btn=e.currentTarget.querySelector('button'),err=body.querySelector('#s2s-chat-error'),message=input.value.trim();if(!message)return;btn.disabled=true;err.textContent='';try{await api('support-send',{method:'POST',body:{conversation_id:session.id,token:session.token,message}});input.value='';await refreshMessages()}catch(x){err.textContent=x.message}finally{btn.disabled=false}};refreshMessages();poller=setInterval(refreshMessages,5000)}
  async function refreshMessages(){if(!session?.id||!session?.token)return;try{const j=await api('support-poll',{query:'&id='+encodeURIComponent(session.id)+'&token='+encodeURIComponent(session.token)});const msgs=j.messages||[],sig=msgs.map(m=>m.id).join('|');if(sig===messagesSignature)return;messagesSignature=sig;const box=body.querySelector('#s2s-messages');if(!box)return;box.innerHTML=msgs.length?msgs.map(m=>'<div class="s2smsg '+(m.sender==='admin'?'admin':'customer')+'">'+esc(m.message)+'<span class="s2stime">'+(m.sender==='admin'?'پشتیبانی':'شما')+' · '+esc(new Date(m.created_at).toLocaleString('fa-IR',{dateStyle:'short',timeStyle:'short'}))+'</span></div>').join(''):'<div class="s2snote">هنوز پیامی نیست. پیام خودت را بفرست تا پشتیبانی پاسخ بدهد.</div>';box.scrollTop=box.scrollHeight;if(j.conversation?.status==='closed'){const err=body.querySelector('#s2s-chat-error');if(err)err.textContent='این گفت‌وگو بسته شده است.'}}catch(e){const err=body.querySelector('#s2s-chat-error');if(err)err.textContent=e.message}}
  root.querySelector('#s2s-support-toggle').onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open')){root.classList.add('open');home()}else{root.classList.remove('open');stopPolling()}};
  root.querySelector('#s2s-support-close').onclick=()=>{panel.classList.remove('open');root.classList.remove('open');stopPolling()};
  window.addEventListener('storage',e=>{if(e.key===KEY){try{session=JSON.parse(e.newValue||'null')}catch(_){session=null}}});
})();