import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!, key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, db=createClient(url,key);
const ADMIN="S2S-V4-2026-ADMIN",EXPERT="S2S-V4-2026-EXPERT";
const J={"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type,authorization"};
const order=["new","refer","inspection","review","auction-ready","auction","auction-end","customer","docs","deposit","contract","done"];
const statusFa:any={new:"تماس اولیه",refer:"تأیید مراجعه کارشناس",inspection:"کارشناسی در حال انجام",review:"پایان کارشناسی","auction-ready":"انتقال به مزایده",auction:"مزایده فعال","auction-end":"پایان مزایده",customer:"مذاکره با مشتری",disagreement:"عدم توافق با مشتری",selling:"در انتظار تصمیم نهایی",docs:"تکمیل مدارک",deposit:"دریافت پیش‌پرداخت",contract:"قرارداد",done:"تکمیل معامله",cancelled:"انصراف"};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:J});
function auth(u:URL){const k=u.searchParams.get("key")||"";return k===ADMIN?"admin":k===EXPERT?"expert":null}
async function listCases(role:string){
 const cq=role==="expert"?db.from("cases").select("*").in("status",["refer","inspection"]).order("created_at",{ascending:false}):db.from("cases").select("*").order("created_at",{ascending:false});
 const {data,error}=await cq;
 if(error)return json({error:error.message},500);
 const ids=(data||[]).map((x:any)=>x.id); let vehicles:any[]=[];
 if(ids.length){const r=await db.from("vehicles").select("*").in("case_id",ids);if(r.error)return json({error:r.error.message},500);vehicles=r.data||[]}
 let inspections:any[]=[]; let defects:any[]=[]; let documents:any[]=[]; let photos:any[]=[]; let history:any[]=[]; let auctions:any[]=[];
 if(ids.length){
  const ir=await db.from("inspections").select("*").in("case_id",ids).order("finished_at",{ascending:false});
  if(ir.error)return json({error:ir.error.message},500); inspections=ir.data||[];
  const ii=inspections.map((x:any)=>x.id);
  if(ii.length){const dr=await db.from("inspection_defects").select("*").in("inspection_id",ii);if(dr.error)return json({error:dr.error.message},500);defects=dr.data||[];const pr=await db.from("inspection_photos").select("*").in("inspection_id",ii);if(pr.error)return json({error:pr.error.message},500);photos=pr.data||[];}
  const xr=await db.from("documents").select("*").in("case_id",ids);if(xr.error)return json({error:xr.error.message},500);documents=xr.data||[];const hr=await db.from("case_history").select("*").in("case_id",ids).order("created_at",{ascending:false});if(hr.error)return json({error:hr.error.message},500);history=hr.data||[];const ar=await db.from("auctions").select("*").in("case_id",ids).order("created_at",{ascending:false});if(ar.error)return json({error:ar.error.message},500);auctions=ar.data||[];
 }
 const mediaRows=[...documents,...photos]; const paths=mediaRows.map((x:any)=>x.storage_path).filter(Boolean); const signed=paths.length?(await db.storage.from("s2s-documents").createSignedUrls(paths,3600)).data||[]:[]; const mediaUrl=(p:string)=>signed.find((x:any)=>x.path===p)?.signedUrl||null;
 return json({cases:(data||[]).map((c:any)=>{const cd=documents.filter((d:any)=>d.case_id===c.id).map((d:any)=>({...d,url:mediaUrl(d.storage_path)}));const cp=inspections.filter((i:any)=>i.case_id===c.id).flatMap((i:any)=>photos.filter((p:any)=>p.inspection_id===i.id)).map((p:any)=>({...p,url:mediaUrl(p.storage_path)}));return {...c,vehicles:vehicles.filter((v:any)=>v.case_id===c.id),inspection:(inspections.find((i:any)=>i.case_id===c.id)||null),defects:inspections.filter((i:any)=>i.case_id===c.id).flatMap((i:any)=>defects.filter((d:any)=>d.inspection_id===i.id)),documents:cd,photos:cp,history:history.filter((h:any)=>h.case_id===c.id),auction:(auctions.find((a:any)=>a.case_id===c.id)||null)}}),statusFa});
}
async function saveDraft(req:Request,id:string){const b=await req.json();const data=b.data&&typeof b.data==="object"?b.data:{};const {error}=await db.from("inspection_drafts").upsert({case_id:id,data,updated_at:new Date().toISOString()},{onConflict:"case_id"});return error?json({error:error.message},500):json({ok:true})}
async function getDraft(id:string){const {data,error}=await db.from("inspection_drafts").select("data,updated_at").eq("case_id",id).maybeSingle();return error?json({error:error.message},500):json({ok:true,draft:data||null})}async function sha256Hex(v:string){const d=new TextEncoder().encode(v);const h=await crypto.subtle.digest("SHA-256",d);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function randCode(){return String(Math.floor(100000+Math.random()*900000))}
function randToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
async function auctionToken(req:Request,u:URL){const h=req.headers.get("authorization")||"";const q=u.searchParams.get("token")||"";const t=(h.startsWith("Bearer ")?h.slice(7):q).trim();if(!t)return null;const th=await sha256Hex(t);const r=await db.from("auction_sessions").select("id,member_id,expires_at").eq("token_hash",th).gt("expires_at",new Date().toISOString()).maybeSingle();return r.data||null}
async function sendAuctionCode(mobile:string,code:string){const hook=Deno.env.get("SMS_WEBHOOK_URL")||"";if(!hook)return false;try{const r=await fetch(hook,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mobile,code,template:"S2S_AUCTION_LOGIN"})});return r.ok}catch(_){return false}}
async function requestAuctionOtp(req:Request){const b=await req.json(),mobile=String(b.mobile||"").replace(/\s/g,""),name=String(b.full_name||"").trim();if(!/^09\d{9}$/.test(mobile))return json({error:"شماره موبایل معتبر نیست"},400);const recent=await db.from("auction_otp_codes").select("created_at").eq("mobile",mobile).order("created_at",{ascending:false}).limit(1).maybeSingle();if(recent.data&&Date.now()-new Date(recent.data.created_at).getTime()<60000)return json({error:"لطفاً ۶۰ ثانیه بعد دوباره درخواست کد کنید"},429);const code=randCode(),hash=await sha256Hex(code);await db.from("auction_otp_codes").insert({mobile,code_hash:hash,display_code:code,expires_at:new Date(Date.now()+5*60000).toISOString()});await db.from("auction_members").upsert({mobile,full_name:name||null,updated_at:new Date().toISOString()},{onConflict:"mobile"});return json({ok:true,delivery:"screen",code,message:"کد ورود شما آماده است؛ کد را فقط نزد خودتان نگه دارید."})}
async function verifyAuctionOtp(req:Request){const b=await req.json(),mobile=String(b.mobile||"").replace(/\s/g,""),code=String(b.code||"").trim();if(!/^09\d{9}$/.test(mobile)||!/^\d{6}$/.test(code))return json({error:"شماره موبایل یا کد نامعتبر است"},400);const r=await db.from("auction_otp_codes").select("*").eq("mobile",mobile).is("verified_at",null).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!r.data)return json({error:"کد پیدا نشد؛ دوباره درخواست کد کنید"},400);if(new Date(r.data.expires_at).getTime()<Date.now())return json({error:"کد منقضی شده است"},400);if(Number(r.data.attempts)>=5)return json({error:"تعداد تلاش بیش از حد مجاز است"},429);const h=await sha256Hex(code);if(h!==r.data.code_hash){await db.from("auction_otp_codes").update({attempts:Number(r.data.attempts)+1}).eq("id",r.data.id);return json({error:"کد واردشده صحیح نیست"},400)}await db.from("auction_otp_codes").update({verified_at:new Date().toISOString()}).eq("id",r.data.id);const mr=await db.from("auction_members").select("*").eq("mobile",mobile).single();if(mr.error)return json({error:mr.error.message},500);const raw=randToken(),th=await sha256Hex(raw);await db.from("auction_sessions").insert({member_id:mr.data.id,token_hash:th,expires_at:new Date(Date.now()+12*60*60000).toISOString()});return json({ok:true,verified:true,subscription_required:false,token:raw,expires_in:43200})}
async function startAuctionSubscription(req:Request){const b=await req.json(),mobile=String(b.mobile||"").replace(/\s/g,""),name=String(b.full_name||"").trim();if(!/^09\d{9}$/.test(mobile))return json({error:"شماره موبایل معتبر نیست"},400);const mr=await db.from("auction_members").upsert({mobile,full_name:name||null,subscription_status:"pending",updated_at:new Date().toISOString()},{onConflict:"mobile"}).select("id,mobile,full_name,subscription_status").single();if(mr.error)return json({error:mr.error.message},500);const url=Deno.env.get("AUCTION_PAYMENT_URL")||"";return json({ok:true,member:mr.data,payment_required:true,amount:Number(Deno.env.get("AUCTION_SUBSCRIPTION_AMOUNT")||0),payment_url:url||null,message:url?"برای پرداخت اشتراک وارد درگاه شوید.":"درگاه پرداخت هنوز تنظیم نشده است."})}
async function auctionLoginCodes(u:URL){const {data,error}=await db.from("auction_otp_codes").select("id,mobile,display_code,created_at,expires_at,verified_at").is("verified_at",null).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(30);return error?json({error:error.message},500):json({ok:true,codes:data||[]})}
async function activateAuctionMember(u:URL,req:Request){const b=await req.json();const mobile=String(b.mobile||"").replace(/\s/g,"");const days=Math.max(1,Number(b.days||30));if(!/^09\d{9}$/.test(mobile))return json({error:"شماره موبایل معتبر نیست"},400);const until=new Date(Date.now()+days*86400000).toISOString();const r=await db.from("auction_members").update({subscription_status:"active",paid_at:new Date().toISOString(),paid_until:until,updated_at:new Date().toISOString()}).eq("mobile",mobile).select("id,mobile,full_name,subscription_status,paid_until").single();return r.error?json({error:r.error.message},500):json({ok:true,member:r.data})}
async function paymentCallback(req:Request){const secret=Deno.env.get("PAYMENT_WEBHOOK_SECRET")||"",got=req.headers.get("x-payment-secret")||"";if(!secret||got!==secret)return json({error:"unauthorized"},401);const b=await req.json(),mobile=String(b.mobile||"").replace(/\s/g,"");if(b.paid!==true)return json({ok:true,ignored:true});const days=Math.max(1,Number(b.days||30));const until=new Date(Date.now()+days*86400000).toISOString();const r=await db.from("auction_members").update({subscription_status:"active",paid_at:new Date().toISOString(),paid_until:until,updated_at:new Date().toISOString()}).eq("mobile",mobile);return r.error?json({error:r.error.message},500):json({ok:true})}
async function publicAuctions(req:Request,u:URL){const sess=await auctionToken(req,u);if(!sess)return json({error:"auction_login_required"},401);const {data:aucs,error}=await db.from("auctions").select("id,case_id,vehicle_id,status,starts_at,ends_at,current_bid,starting_price,created_at").eq("status","active").order("created_at",{ascending:false});if(error)return json({error:error.message},500);const out:any[]=[];for(const a of (aucs||[])){if(new Date(a.ends_at).getTime()<=Date.now()){await db.from("auctions").update({status:"ended"}).eq("id",a.id);await db.from("cases").update({status:"auction-end"}).eq("id",a.case_id);continue;}const cr=await db.from("cases").select("id,case_number").eq("id",a.case_id).single();const vr=await db.from("vehicles").select("id,brand,model,trim,model_year,color,mileage,body_condition,technical_condition,general_condition").eq("id",a.vehicle_id).maybeSingle();const ir=await db.from("inspections").select("id,summary,finished_at,status").eq("case_id",a.case_id).order("finished_at",{ascending:false}).limit(1).maybeSingle();let defects:any[]=[],photos:any[]=[];if(ir.data?.id){const dr=await db.from("inspection_defects").select("area,part,defect_type,explanation").eq("inspection_id",ir.data.id);defects=dr.data||[];const pr=await db.from("inspection_photos").select("photo_type,label,storage_path,annotation").eq("inspection_id",ir.data.id).neq("photo_type","document");photos=pr.data||[];}const br=await db.from("bids").select("id,amount,bidder_name,created_at").eq("auction_id",a.id).order("created_at",{ascending:false});const paths=photos.map((x:any)=>x.storage_path).filter(Boolean);const signed=paths.length?(await db.storage.from("s2s-documents").createSignedUrls(paths,3600)).data||[]:[];const mediaUrl=(p:string)=>signed.find((x:any)=>x.path===p)?.signedUrl||null;out.push({...a,case:cr.data||null,vehicle:vr.data||null,inspection:ir.data||null,defects,photos:photos.map((p:any)=>({...p,url:mediaUrl(p.storage_path)})),bids:br.data||[]});}return json({auctions:out});}
async function placeBid(req:Request,id:string){
 const u=new URL(req.url),sess=await auctionToken(req,u);
 if(!sess)return json({error:"auction_login_required"},401);
 const b=await req.json(),amount=Number(b.amount||0);
 if(!Number.isFinite(amount)||amount<=0)return json({error:"مبلغ پیشنهاد نامعتبر است"},400);
 const mr=await db.from("auction_members").select("full_name,mobile").eq("id",sess.member_id).single();
 if(mr.error)return json({error:"عضویت مزایده معتبر نیست"},403);
 const r=await db.rpc("place_auction_bid",{
   p_auction_id:id,
   p_member_id:sess.member_id,
   p_amount:amount,
   p_bidder_name:mr.data.full_name||"خریدار",
   p_bidder_mobile:mr.data.mobile
 });
 if(r.error){
   const msg=r.error.message||"ثبت پیشنهاد ناموفق بود";
   return json({error:msg},400);
 }
 return json({ok:true,bid:r.data,current_bid:Number(r.data.current_bid)});
}
async function inspect(req:Request,id:string){
 const b=await req.json();if(!b.vin||!b.engine_number||!b.plate_number||!b.national_id_data_url)return json({error:"VIN، شماره موتور، پلاک و عکس کارت ملی مالک الزامی است"},400);
 const {data:v}=await db.from("vehicles").select("id").eq("case_id",id).eq("vehicle_role","current").limit(1).maybeSingle();
 if(v)await db.from("vehicles").update({vin:b.vin,engine_number:b.engine_number,plate_number:b.plate_number,spare_key:!!b.spare_key,fuel_card:!!b.fuel_card,power_of_attorney:!!b.power_of_attorney}).eq("id",v.id);
 const {data:i,error:ie}=await db.from("inspections").insert({case_id:id,status:"completed",finished_at:new Date().toISOString(),summary:b.summary||"کارشناسی ثبت شد"}).select("id").single();if(ie)return json({error:ie.message},500);
 const raw=b.national_id_data_url.split(","),mime=(raw[0].match(/data:(.*?);base64/)||[])[1]||"image/jpeg",bytes=Uint8Array.from(atob(raw[1]),c=>c.charCodeAt(0)),path=`${id}/national-id-${Date.now()}.jpg`;
 const up=await db.storage.from("s2s-documents").upload(path,bytes,{contentType:mime,upsert:false});if(up.error)return json({error:"آپلود کارت ملی ناموفق بود: "+up.error.message},500);
 await db.from("documents").insert({case_id:id,vehicle_id:v?.id||null,document_type:"owner_national_id",storage_path:path,required:true});
 if(Array.isArray(b.documents))for(const d of b.documents){if(!d?.data_url)continue;const raw=d.data_url.split(","),mime=(raw[0].match(/data:(.*?);base64/)||[])[1]||"image/jpeg",bytes=Uint8Array.from(atob(raw[1]),c=>c.charCodeAt(0)),path=`${id}/documents/\${crypto.randomUUID()}.jpg`;const up=await db.storage.from("s2s-documents").upload(path,bytes,{contentType:mime,upsert:false});if(up.error)throw Error("آپلود مدرک ناموفق بود: "+up.error.message);await db.from("documents").insert({case_id:id,vehicle_id:v?.id||null,document_type:d.type||"other",storage_path:path,required:false});}
 if(Array.isArray(b.main_photos))for(const m of b.main_photos){if(!m?.data_url)continue;const raw=m.data_url.split(","),mime=(raw[0].match(/data:(.*?);base64/)||[])[1]||"image/jpeg",bytes=Uint8Array.from(atob(raw[1]),c=>c.charCodeAt(0)),path=`${id}/inspection/main-\${crypto.randomUUID()}.jpg`;const up=await db.storage.from("s2s-documents").upload(path,bytes,{contentType:mime,upsert:false});if(up.error)throw Error("آپلود عکس اصلی ناموفق بود: "+up.error.message);await db.from("inspection_photos").insert({inspection_id:i.id,photo_type:"main",label:m.label||"عکس اصلی خودرو",storage_path:path,annotation:m.annotation||null});}
 if(Array.isArray(b.defects))for(const d of b.defects){if(!d?.part||!d?.defect_type)continue;const q=await db.from("inspection_defects").insert({inspection_id:i.id,area:d.area||"بدنه",part:d.part,defect_type:d.defect_type,explanation:d.explanation||""}).select("id").single();if(q.error)throw Error(q.error.message);for(const p0 of (d.photos||[])){if(!p0?.data_url)continue;const raw=p0.data_url.split(","),mime=(raw[0].match(/data:(.*?);base64/)||[])[1]||"image/jpeg",bytes=Uint8Array.from(atob(raw[1]),c=>c.charCodeAt(0)),path=`${id}/inspection/defect-\${crypto.randomUUID()}.jpg`;const up=await db.storage.from("s2s-documents").upload(path,bytes,{contentType:mime,upsert:false});if(up.error)throw Error("آپلود عکس ایراد ناموفق بود: "+up.error.message);await db.from("inspection_photos").insert({inspection_id:i.id,defect_id:q.data.id,photo_type:"defect",label:d.part+" • "+d.defect_type,storage_path:path,annotation:p0.annotation||null});}}
 await db.from("cases").update({status:"review"}).eq("id",id);return json({ok:true});
}
async function marketPrices(u:URL){ const brand=u.searchParams.get("brand")||""; const model=u.searchParams.get("model")||""; const trim=u.searchParams.get("trim")||""; let q=db.from("vehicle_market_prices").select("*").order("updated_at",{ascending:false}).limit(100); if(brand)q=q.eq("brand",brand); if(model)q=q.eq("model",model); if(trim)q=q.eq("trim",trim); const {data,error}=await q; return error?json({error:error.message},500):json({prices:data||[]}); }
async function estimate(req:Request){
 const b=await req.json(); const brand=b.brand||"",model=b.model||"",trim=b.trim||"",year=Number(b.year||0),km=Number(b.mileage||0),body=b.body_condition||"clean";
 if(!brand||!model||!year||!km)return json({error:"brand, model, year and mileage are required"},400);
 let q=db.from("vehicle_market_prices").select("price,updated_at,trim,model_year,calendar").eq("brand",brand).eq("model",model).order("updated_at",{ascending:false}).limit(8); if(trim)q=q.eq("trim",trim); const {data}=await q;
 const vals=(data||[]).map((x:any)=>Number(x.price)).filter((x:number)=>x>0);
 if(!vals.length)return json({ok:false,source:"no_market_data",message:"برای این مدل قیمت بازار ثبت نشده است."},200);
 const zero=vals.reduce((a:number,v:number)=>a+v,0)/vals.length;
 const age=Math.max(0,1405-year);
 const ageFactor=Math.pow(0.955,Math.min(age,12));
 const mileageFactor=km<=30000?1:Math.max(0.68,1-((km-30000)/100000)*0.035);
 const bodyFactor=({clean:1,minor:0.94,painted:0.88,full:0.80,accident:0.68} as any)[body]||1;
 const estimated=Math.max(150000000,zero*ageFactor*mileageFactor*bodyFactor);
 const low=estimated*0.93,high=estimated*1.07;
 return json({ok:true,source:"market_based_used",source_label:"برآورد بر پایه قیمت روز بازار + سال، کارکرد و وضعیت بدنه",average_price:Math.round(estimated),low_price:Math.round(low),high_price:Math.round(high),zero_reference:Math.round(zero),sample_count:vals.length,updated_at:data?.[0]?.updated_at||new Date().toISOString()});
}async function historyAdd(id:string,from:string,to:string,note:string){await db.from("case_history").insert({case_id:id,from_status:from,to_status:to,note});} async function setStatus(id:string,next:string,note:string){const {data,error}=await db.from("cases").select("status").eq("id",id).single();if(error)return json({error:error.message},500);const r=await db.from("cases").update({status:next}).eq("id",id);if(r.error)return json({error:r.error.message},500);await historyAdd(id,data?.status||"new",next,note);return json({ok:true,status:next})} async function caseComments(req:Request,id:string,role:string){
 if(!id)return json({error:"پرونده مشخص نیست"},400);
 const cr=await db.from("cases").select("id,status").eq("id",id).maybeSingle();
 if(cr.error)return json({error:cr.error.message},500);
 if(!cr.data)return json({error:"پرونده پیدا نشد"},404);
 if(role==="expert"&&!["refer","inspection"].includes(cr.data.status))return json({error:"این پرونده در حال حاضر در دسترس کارشناس نیست"},403);
 if(req.method==="GET"){
  const r=await db.from("case_comments").select("id,case_id,author_role,message,created_at").eq("case_id",id).order("created_at",{ascending:true});
  return r.error?json({error:r.error.message},500):json({comments:r.data||[]});
 }
 if(req.method==="POST"){
  const b=await req.json(),message=String(b.message||"").trim();
  if(!message)return json({error:"متن پیام را بنویسید"},400);
  if(message.length>3000)return json({error:"پیام نباید بیشتر از ۳۰۰۰ نویسه باشد"},400);
  const r=await db.from("case_comments").insert({case_id:id,author_role:role,message}).select("id,case_id,author_role,message,created_at").single();
  return r.error?json({error:r.error.message},500):json({ok:true,comment:r.data});
 }
 return json({error:"method_not_allowed"},405);
}
async function expireAuctions(){const now=new Date().toISOString();const {data,error}=await db.from("auctions").select("id,case_id,current_bid").eq("status","active").lte("ends_at",now).limit(100);if(error||!data?.length)return;for(const a of data){const br=await db.from("bids").select("buyer_id,amount").eq("auction_id",a.id).order("amount",{ascending:false}).limit(1).maybeSingle();const winner=br.data?.buyer_id||null;const finalBid=Number(br.data?.amount||a.current_bid||0);const up=await db.from("auctions").update({status:"ended",winner_id:winner,current_bid:finalBid}).eq("id",a.id).eq("status","active").select("id").maybeSingle();if(up.data){await db.from("cases").update({status:"auction-end"}).eq("id",a.case_id).eq("status","auction");await historyAdd(a.case_id,"auction","auction-end",winner?"پایان خودکار مزایده پس از ۶۰ دقیقه؛ برنده مشخص شد":"پایان خودکار مزایده پس از ۶۰ دقیقه؛ بدون برنده");}}}
async function api(req:Request,u:URL){
 const role=auth(u),a=u.searchParams.get("api"),id=u.searchParams.get("id")||"";
 await expireAuctions();
 if(a==="public-ready-auctions"&&req.method==="GET"){const {data,error}=await db.from("cases").select("id,case_number,status,created_at").eq("status","review").order("created_at",{ascending:false});if(error)return json({error:error.message},500);const ids=(data||[]).map((c:any)=>c.id);const vr=ids.length?await db.from("vehicles").select("case_id,brand,model,trim,model_year,mileage").in("case_id",ids).eq("vehicle_role","current"):{data:[],error:null};if(vr.error)return json({error:vr.error.message},500);return json({cases:(data||[]).map((c:any)=>({...c,vehicle:(vr.data||[]).find((v:any)=>v.case_id===c.id)||null}))})}if(a==="auction-request-code"&&req.method==="POST")return requestAuctionOtp(req);if(a==="auction-verify-code"&&req.method==="POST")return verifyAuctionOtp(req);if(a==="auction-start-subscription"&&req.method==="POST")return startAuctionSubscription(req);if(a==="auction-payment-callback"&&req.method==="POST")return paymentCallback(req);if(a==="public-auctions"&&req.method==="GET")return publicAuctions(req,u);
 if(a==="place-bid"&&req.method==="POST")return placeBid(req,id);
 if(a==="market_prices")return marketPrices(u); if(a==="estimate"&&req.method==="POST")return estimate(req);
 if(a==="auction-login-codes"&&role==="admin"&&req.method==="GET")return auctionLoginCodes(u);
if(a==="activate-auction-member"&&role==="admin"&&req.method==="POST")return activateAuctionMember(u,req);if(!role)return json({error:"unauthorized"},401);
 if(a==="list")return listCases(role);
 if(a==="case-comments"&&req.method==="GET")return caseComments(req,id,role);
 if(a==="case-comment"&&req.method==="POST")return caseComments(req,id,role);
 if(a==="draft"&&role==="expert"&&req.method==="GET")return getDraft(id);
 if(a==="draft"&&role==="expert"&&req.method==="POST")return saveDraft(req,id);
 if(a==="auctions"&&role==="admin"){const {data,error}=await db.from("auctions").select("*").order("created_at",{ascending:false});if(error)return json({error:error.message},500);const ids=(data||[]).map((x:any)=>x.case_id).filter(Boolean);let cases:any[]=[];if(ids.length){const cr=await db.from("cases").select("*").in("id",ids);if(cr.error)return json({error:cr.error.message},500);cases=cr.data||[]}const aids=(data||[]).map((x:any)=>x.id);let bids:any[]=[];if(aids.length){const br=await db.from("bids").select("*").in("auction_id",aids).order("amount",{ascending:false});if(br.error)return json({error:br.error.message},500);bids=br.data||[]}return json({auctions:(data||[]).map((a:any)=>({...a,case:cases.find((c:any)=>c.id===a.case_id)||null,bids:bids.filter((b:any)=>b.auction_id===a.id)}))})}
if(a==="eligible-auctions"&&role==="admin"){const {data,error}=await db.from("cases").select("*").eq("status","review").order("created_at",{ascending:false});return error?json({error:error.message},500):json({cases:data||[]})}
if(a==="create_auction"&&role==="admin"){const b=await req.json();if(!id||!b.starting_price||Number(b.starting_price)<=0)return json({error:"پرونده و قیمت شروع الزامی است"},400);const cr=await db.from("cases").select("id,status").eq("id",id).single();if(cr.error)return json({error:"پرونده پیدا نشد"},404);if(!["review","auction-ready"].includes(cr.data.status))return json({error:"ابتدا پایان کارشناسی را تأیید و پرونده را به مرحله انتقال به مزایده ببرید"},400);const ex=await db.from("auctions").select("id,status").eq("case_id",id).eq("status","active").maybeSingle();if(ex.data)return json({error:"برای این پرونده یک مزایده فعال از قبل وجود دارد"},409);const vr=await db.from("vehicles").select("id").eq("case_id",id).eq("vehicle_role","current").limit(1).maybeSingle();const starts=new Date();const ends=new Date(starts.getTime()+60*60000);const ar=await db.from("auctions").insert({case_id:id,vehicle_id:vr.data?.id||null,status:"active",starts_at:starts.toISOString(),ends_at:ends.toISOString(),starting_price:Number(b.starting_price),current_bid:Number(b.starting_price)}).select("*").single();if(ar.error)return json({error:ar.error.message},500);await db.from("cases").update({status:"auction"}).eq("id",id);await historyAdd(id,cr.data.status,"auction","مزایده به‌صورت خودکار با زمان ثابت ۶۰ دقیقه شروع شد");return json({ok:true,auction:ar.data})}
if(a==="update_auction_time"&&role==="admin")return json({error:"مدت هر مزایده ثابت است و دقیقاً ۶۰ دقیقه خواهد بود"},400)if(a==="end_auction"&&role==="admin"){const ar=await db.from("auctions").select("*").eq("id",id).single();if(ar.error)return json({error:"مزایده پیدا نشد"},404);if(ar.data.status!=="active")return json({error:"این مزایده فعال نیست"},400);const br=await db.from("bids").select("*").eq("auction_id",id).order("amount",{ascending:false}).limit(1).maybeSingle();if(br.error)return json({error:br.error.message},500);const winner=br.data?.buyer_id||null;const upd=await db.from("auctions").update({status:"ended",winner_id:winner,current_bid:br.data?.amount||ar.data.current_bid}).eq("id",id);if(upd.error)return json({error:upd.error.message},500);await db.from("cases").update({status:"auction-end"}).eq("id",ar.data.case_id);await historyAdd(ar.data.case_id,"auction","auction-end",winner?"مزایده پایان یافت و برنده مشخص شد":"مزایده پایان یافت بدون برنده");return json({ok:true,winner_id:winner,current_bid:br.data?.amount||ar.data.current_bid})}
 if(a==="confirm-call"&&role==="admin")return setStatus(id,"refer","تأیید تلفنی مشتری");if(a==="customer-decision"&&role==="admin"){const b=await req.json();if(!["accept","decline"].includes(b.decision))return json({error:"decision_invalid"},400);const next=b.decision==="accept"?"docs":"disagreement";const r=await db.from("cases").update({status:next,agreed_price:b.decision==="accept"?(Number(b.agreed_price||0)||null):null,customer_decision_at:new Date().toISOString(),customer_decision_note:b.note||null}).eq("id",id);if(r.error)return json({error:r.error.message},500);await historyAdd(id,"customer",next,b.decision==="accept"?"مشتری قیمت را پذیرفت":"عدم توافق با قیمت");return json({ok:true,status:next})}if(a==="prepayment"&&role==="admin"){const b=await req.json(),amount=Number(b.amount||0);if(amount<=0)return json({error:"مبلغ پیش‌پرداخت نامعتبر است"},400);const r=await db.from("cases").update({status:"contract",prepayment_amount:amount,prepayment_status:"received",prepayment_received_at:new Date().toISOString()}).eq("id",id);if(r.error)return json({error:r.error.message},500);await historyAdd(id,"deposit","contract","پیش‌پرداخت دریافت شد: "+amount);return json({ok:true,status:"contract"})}if(a==="continue-selling"&&role==="admin")return setStatus(id,"selling","ادامه فعالیت برای فروش خودرو");if(a==="set-status"&&role==="admin"){const b=await req.json();if(!b.status||!statusFa[b.status])return json({error:"status_invalid"},400);if(["review","auction"].includes(b.status))return json({error:"این مرحله فقط از مسیر اختصاصی کارشناسی یا شروع مزایده قابل ثبت است"},403);if(b.status==="inspection"){const cr=await db.from("cases").select("status").eq("id",id).single();if(cr.error)return json({error:"پرونده پیدا نشد"},404);if(!["refer","inspection"].includes(cr.data.status))return json({error:"ابتدا پرونده را به کارشناس ارجاع دهید"},400)}return setStatus(id,b.status,b.note||"تغییر وضعیت توسط مدیر")}if(a==="expert-status"&&role==="expert"){const b=await req.json();if(!["inspection","review"].includes(b.status))return json({error:"status_invalid"},400);const cr=await db.from("cases").select("status").eq("id",id).single();if(cr.error)return json({error:"پرونده پیدا نشد"},404);if(b.status==="review"&&cr.data.status!=="inspection")return json({error:"فقط کارشناسِ پرونده در حال کارشناسی می‌تواند پایان کارشناسی را ثبت کند"},403);if(b.status==="inspection"&&!["refer","inspection"].includes(cr.data.status))return json({error:"پرونده هنوز به کارشناس ارجاع نشده"},400);return setStatus(id,b.status,b.note||(b.status==="inspection"?"کارشناس شروع به کارشناسی کرد":"کارشناسی پایان یافت"))}if(req.method!=="POST")return json({error:"method_not_allowed"},405);
 if(a==="next"&&role==="admin"){const {data,error}=await db.from("cases").select("status").eq("id",id).single();if(error)return json({error:error.message},500);const i=order.indexOf(data?.status||"new"),next=order[Math.min(i+1,order.length-1)];return setStatus(id,next,"مرحله بعد")}
 if(a==="cancel"&&role==="admin")return setStatus(id,"cancelled","انصراف");
 if(a==="inspect"&&role==="expert")return inspect(req,id);
 return json({error:"not_found"},404)
}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:J});const u=new URL(req.url);if(u.searchParams.has("api"))return api(req,u);
 if(req.method==="POST"){try{const b=await req.json();if(!b.name||!b.mobile||!["sell","buy","exchange"].includes(b.type))return json({error:"نام، موبایل و نوع درخواست الزامی است"},400);
 const {data:c,error}=await db.from("cases").insert({service_type:b.type,customer_name:b.name,customer_mobile:b.mobile,notes:String(b.notes||"").trim()||null,appointment_date:b.type==="sell"?b.appointment_date||null:null,appointment_time:b.type==="sell"?b.appointment_time||null:null}).select("id,case_number").single();
 if(error){if(error.code==="23505"&&error.message.includes("cases_unique_active_appointment"))return json({error:"این روز و ساعت قبلاً رزرو شده است. لطفاً یک زمان دیگر انتخاب کنید.",code:"appointment_taken"},409);return json({error:error.message},500)}
 const vs:any[]=[];if(b.vehicle)vs.push({...b.vehicle,vehicle_role:"current"});if(b.target_vehicle)vs.push({...b.target_vehicle,vehicle_role:"target"});for(const v of vs){const x={...v,case_id:c.id};delete x.budget;const r=await db.from("vehicles").insert(x);if(r.error)return json({error:"پرونده ساخته شد اما ذخیره خودرو ناموفق بود: "+r.error.message,case_number:c.case_number,id:c.id},500)}
 return json({ok:true,case_number:c.case_number,id:c.id})}catch(e){return json({error:String(e)},500)}}return json({ok:true,service:"switch-to-switch-v4-api"})});